### PR TITLE
More generative awesomeness

### PR DESCRIPTION
**Pull request by anissen**
Great project you've started here! I think I'll have a lot of resources to contribute with. Here's a few for starters :)

### CODE REVIEW

**Comment by anissen** [comment]
Oh, it's only for generative _art_? In that case `traceryhx` probably shouldn't be included...

**Comment by MatthijsKamstra** [comment]
oh no, I was just looking around for stuff... so anything is welcome
I was just constructing a small list because I ran into problems starting with this.

Thx

**Comment by MatthijsKamstra** [comment]
btw you are fast! I just created this list.

**Comment by MatthijsKamstra** [comment]
@anissen any idea who to ping (in a tweet)? I was thinking Mark Knol but others I'm not sure about

**Comment by anissen** [comment]
_Definitely_ Mark Knol! Also [skial](https://twitter.com/skial), [lewislepton](https://twitter.com/lewislepton) and [#haxe](https://twitter.com/hashtag/Haxe?src=hash). Maybe [nadako](https://twitter.com/nadako), [polygonal](https://twitter.com/polygonal) and [azrafe7](https://twitter.com/azrafe7).

**Comment by MatthijsKamstra** [comment]
done: https://twitter.com/MatthijsKamstra/status/808645667635757056

thx again for you input

**Pull request merged**
